export default {
    physical_attack: '物理攻击',
    magic_attack: '法术攻击',
    attack_speed_percentage: '%攻击速度',
    crit_rate_percentage: '%暴击率',
    physical_blood_draw_percentage: '%物理吸血',
    cooling_shortening_percentage: '%减CD',
    moving_speed: '移动速度',
    moving_speed_percentage: '%移速',
    spell_vampire_percentage: '%法术吸血',
    physical_penetration: '',
    magic_penetration: '',
    physical_defense: '物理防御',
    magic_defense: '法术防御',
    maximum_life: '最大生命',
    maximum_magic: '最大法力',
    return_blood: '',
    crit_effect: '',
    return_magic: '',
};
